### ISSUE TITLE
Unable to resolve dependency

### ISSUE THREAD

**Issue by marvesimate** [dev-ritik/EmojiReactionView#6]
I'm getting the following errors when i try to build gradle after adding the library, kindly help

Unable to resolve dependency for ':app@debugAndroidTest/compileClasspath': Could not find  com.ritik:emojireactionlibrary:1.0.1.

Unable to resolve dependency for ':app@debugUnitTest/compileClasspath': Could not find  com.ritik:emojireactionlibrary:1.0.1.

Unable to resolve dependency for ':app@release/compileClasspath': Could not find  com.ritik:emojireactionlibrary:1.0.1.

Unable to resolve dependency for ':app@releaseUnitTest/compileClasspath': Could not find  com.ritik:emojireactionlibrary:1.0.1.

**Comment by marvesimate** [comment]
I was getting the issue because of a space when implementing the library 
implementation ' com.ritik:emojireactionlibrary:1.0.1'

**Comment by dev-ritik** [comment]
cool!!
