### ISSUE TITLE
On EmojiClicklistener not triggering 

### ISSUE THREAD

**Issue by marvesimate** [dev-ritik/EmojiReactionView#7]
I have done a basic implementation but when i click on the home emoji, there is no animation and the other emojis don't pop up

**Comment by dev-ritik** [comment]
Hi @marvesimate 

The bug you encountered has been fixed in the latest commit but unfortunately, I didn't have time enough to update the dependency!.
For the time being, you can use other hosting platforms for the same. Meanwhile, I shall try to update the bintray dependency as soon as possible.

**Comment by dev-ritik** [comment]
So @marvesimate , I have uploaded the repository to jitpack for the moment.

Direction to add:
Add it in your root build.gradle at the end of repositories
`allprojects {
		repositories {
			...
			maven { url 'https://jitpack.io' }
		}
	}`

 Add the dependency
`dependencies {
	        implementation 'com.github.dev-ritik:EmojiReactionView:07aa16ce4f'
	}`

Hope it resolves the bug.

**Comment by dev-ritik** [comment]
Hi @marvesimate 
Sorry for the delay.
The updated dependency is now available in the README file! :tada:

**Comment by marvesimate** [comment]
great thanks!
