### ISSUE TITLE
EmojiUnclicked Triggers without clicking the emoji

### ISSUE THREAD

**Issue by marvesimate** [dev-ritik/EmojiReactionView#8]
When the emoji reactionview is used in a recycle view emojiunclicked is triggered when the adapter is being loaded, i tried it in the sample its behaves the same way

**Comment by dev-ritik** [comment]
Hey @marvesimate,
The Adapter in recycler view binds views for the objects of the model class as and when required. In the process, it calls `setClickedEmojiNumber` as in the sample app. So, it continuously triggers `onEmojiUnclicked` interface method.
The best way out is to check the value of parameters `x` and `y`. If they are both `-1` , this means that it has been called by the program not by a user. This is clearly mentioned in the README file. All you can do is ignore it with an appropriate conditional statement.

**Comment by marvesimate** [comment]
Thanks for the clarification, it makes more sense now
